## isin()
#### it checks if the DataFrame contains the specified values
#### it returns DataFrame similar to original DataFrame,but original values are replaced with True if they are present,otherwise False

### Find the most destructive death over batsman in the history of IPL

### Strike Rate = (Number of runs/Number of balls) * 100

### Min batsman 200 balls in over 16-20

In [2]:
import numpy as np
import pandas as pd
delivery=pd.read_csv("deliveries.csv")

In [3]:
delivery

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [10]:
# display only the death overs information
death_over=delivery[delivery["over"]>15]

In [12]:
all_batsman=death_over.groupby("batsman")["batsman_runs"].count()

In [14]:
x=all_batsman>200

In [15]:
all_batsman

batsman
A Ashish Reddy    148
A Chandila          7
A Chopra            2
A Choudhary        20
A Flintoff         18
                 ...
YS Chahal          27
YV Takawale        13
Yashpal Singh      13
Yuvraj Singh      516
Z Khan            109
Name: batsman_runs, Length: 416, dtype: int64

In [16]:
x

batsman
A Ashish Reddy    False
A Chandila        False
A Chopra          False
A Choudhary       False
A Flintoff        False
                  ...
YS Chahal         False
YV Takawale       False
Yashpal Singh     False
Yuvraj Singh       True
Z Khan            False
Name: batsman_runs, Length: 416, dtype: bool

In [17]:
all_batsman[x]

batsman
A Mishra             225
AB de Villiers       570
AD Mathews           289
AM Rahane            268
AR Patel             229
AT Rayudu            425
BJ Hodge             385
DA Miller            360
DA Warner            228
DJ Bravo             409
DJ Hussey            234
DPMD Jayawardene     246
Harbhajan Singh      418
IK Pathan            465
JA Morkel            425
JH Kallis            231
JP Duminy            518
JP Faulkner          294
KA Pollard           838
KD Karthik           463
KM Jadhav            338
LRPL Taylor          204
MK Pandey            224
MK Tiwary            423
MS Dhoni            1224
NV Ojha              304
P Kumar              268
PP Chawla            311
R Vinay Kumar        235
RA Jadeja            576
RG Sharma            748
RV Uthappa           275
S Badrinath          283
S Dhawan             243
SK Raina             458
SPD Smith            316
SS Tiwary            300
STR Binny            218
V Kohli              546
WP Saha              295
Y Venugopal Rao      260
YK Pathan            584
Yuvraj Singh         516
Name: batsman_runs, dtype: int64

In [23]:
all_batsman[x].shape

(43,)

In [19]:
#death_over.groupby("batsman")["batsman_runs"].sum()

In [20]:
batsman_list=all_batsman[x].index.tolist()

In [21]:
batsman_list

['A Mishra',
 'AB de Villiers',
 'AD Mathews',
 'AM Rahane',
 'AR Patel',
 'AT Rayudu',
 'BJ Hodge',
 'DA Miller',
 'DA Warner',
 'DJ Bravo',
 'DJ Hussey',
 'DPMD Jayawardene',
 'Harbhajan Singh',
 'IK Pathan',
 'JA Morkel',
 'JH Kallis',
 'JP Duminy',
 'JP Faulkner',
 'KA Pollard',
 'KD Karthik',
 'KM Jadhav',
 'LRPL Taylor',
 'MK Pandey',
 'MK Tiwary',
 'MS Dhoni',
 'NV Ojha',
 'P Kumar',
 'PP Chawla',
 'R Vinay Kumar',
 'RA Jadeja',
 'RG Sharma',
 'RV Uthappa',
 'S Badrinath',
 'S Dhawan',
 'SK Raina',
 'SPD Smith',
 'SS Tiwary',
 'STR Binny',
 'V Kohli',
 'WP Saha',
 'Y Venugopal Rao',
 'YK Pathan',
 'Yuvraj Singh']

### To calculate the strike rate---we should know
#### Runs scored by all these 43 batsman
#### Balls played by these 43 batsman

In [36]:
death_over=death_over[death_over["batsman"].isin(batsman_list)]

In [37]:
death_over

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
95,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,3,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
97,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,5,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
100,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,2,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
101,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
102,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,4,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150442,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,1,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150443,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,2,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150445,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150446,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150448,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,STR Binny,run out,DJ Hooda

In [38]:
death_over[death_over["batsman"].isin(batsman_list)].shape

(16669, 21)

In [39]:
final=death_over[death_over["batsman"].isin(batsman_list)]

#### to calculate runs

In [40]:
runs=final.groupby("batsman")["batsman_runs"].sum()

In [44]:
runs

batsman
A Mishra             227
AB de Villiers      1203
AD Mathews           425
AM Rahane            410
AR Patel             327
AT Rayudu            703
BJ Hodge             606
DA Miller            672
DA Warner            432
DJ Bravo             686
DJ Hussey            410
DPMD Jayawardene     374
Harbhajan Singh      617
IK Pathan            663
JA Morkel            637
JH Kallis            394
JP Duminy            869
JP Faulkner          439
KA Pollard          1352
KD Karthik           704
KM Jadhav            488
LRPL Taylor          312
MK Pandey            340
MK Tiwary            593
MS Dhoni            2076
NV Ojha              410
P Kumar              294
PP Chawla            374
R Vinay Kumar        256
RA Jadeja            753
RG Sharma           1314
RV Uthappa           477
S Badrinath          422
S Dhawan             386
SK Raina             767
SPD Smith            535
SS Tiwary            410
STR Binny            314
V Kohli              993
WP Saha              482
Y Venugopal Rao      387
YK Pathan            930
Yuvraj Singh         883
Name: batsman_runs, dtype: int64

#### to calculate balls

In [45]:
balls=final.groupby("batsman")["batsman_runs"].count()

In [46]:
balls

batsman
A Mishra             225
AB de Villiers       570
AD Mathews           289
AM Rahane            268
AR Patel             229
AT Rayudu            425
BJ Hodge             385
DA Miller            360
DA Warner            228
DJ Bravo             409
DJ Hussey            234
DPMD Jayawardene     246
Harbhajan Singh      418
IK Pathan            465
JA Morkel            425
JH Kallis            231
JP Duminy            518
JP Faulkner          294
KA Pollard           838
KD Karthik           463
KM Jadhav            338
LRPL Taylor          204
MK Pandey            224
MK Tiwary            423
MS Dhoni            1224
NV Ojha              304
P Kumar              268
PP Chawla            311
R Vinay Kumar        235
RA Jadeja            576
RG Sharma            748
RV Uthappa           275
S Badrinath          283
S Dhawan             243
SK Raina             458
SPD Smith            316
SS Tiwary            300
STR Binny            218
V Kohli              546
WP Saha              295
Y Venugopal Rao      260
YK Pathan            584
Yuvraj Singh         516
Name: batsman_runs, dtype: int64

#### to calculate Strike Rate

In [42]:
sr=(runs/balls)*100

In [43]:
sr

batsman
A Mishra            100.888889
AB de Villiers      211.052632
AD Mathews          147.058824
AM Rahane           152.985075
AR Patel            142.794760
AT Rayudu           165.411765
BJ Hodge            157.402597
DA Miller           186.666667
DA Warner           189.473684
DJ Bravo            167.726161
DJ Hussey           175.213675
DPMD Jayawardene    152.032520
Harbhajan Singh     147.607656
IK Pathan           142.580645
JA Morkel           149.882353
JH Kallis           170.562771
JP Duminy           167.760618
JP Faulkner         149.319728
KA Pollard          161.336516
KD Karthik          152.051836
KM Jadhav           144.378698
LRPL Taylor         152.941176
MK Pandey           151.785714
MK Tiwary           140.189125
MS Dhoni            169.607843
NV Ojha             134.868421
P Kumar             109.701493
PP Chawla           120.257235
R Vinay Kumar       108.936170
RA Jadeja           130.729167
RG Sharma           175.668449
RV Uthappa          173.454545
S Badrinath         149.116608
S Dhawan            158.847737
SK Raina            167.467249
SPD Smith           169.303797
SS Tiwary           136.666667
STR Binny           144.036697
V Kohli             181.868132
WP Saha             163.389831
Y Venugopal Rao     148.846154
YK Pathan           159.246575
Yuvraj Singh        171.124031
Name: batsman_runs, dtype: float64

In [51]:
sr.head(5)

batsman
A Mishra          100.888889
AB de Villiers    211.052632
AD Mathews        147.058824
AM Rahane         152.985075
AR Patel          142.794760
Name: batsman_runs, dtype: float64

### top 5 batsman with highest strike rate

In [53]:
sr.nlargest()

batsman
AB de Villiers    211.052632
DA Warner         189.473684
DA Miller         186.666667
V Kohli           181.868132
RG Sharma         175.668449
Name: batsman_runs, dtype: float64

### 5 batsman with least strike rate

In [54]:
sr.nsmallest()

batsman
A Mishra         100.888889
R Vinay Kumar    108.936170
P Kumar          109.701493
PP Chawla        120.257235
RA Jadeja        130.729167
Name: batsman_runs, dtype: float64

In [55]:
sr.nsmallest(3)

batsman
A Mishra         100.888889
R Vinay Kumar    108.936170
P Kumar          109.701493
Name: batsman_runs, dtype: float64